<%@ Page Title="" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeFile="IELayoutEdit.aspx.cs" Inherits="IELayoutEdit" %>


<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="asp" %>

<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" Runat="Server">
    <asp:UpdatePanel ID="UpdatePanel1" runat="server">
        <ContentTemplate>
            <div>
                 <fieldset style="float:left;margin-right:100px;" > 
                     <table>
                            <tr>
                             
                                <td height="18px" width="100px">
                                    <span class="sp1">STYLE INFO</span>
                                </td>
                                <td>
                                </td>
                                <td>
                                </td>
                            </tr>
                        
                          <tr>
                                <td height="18px" width="180px">
                                    <span class="text-primary">Buyer </span>
                                </td>
                                <td>
                                    <asp:DropDownList ID="GetByr" runat="server" CssClass="textbox" Width="200px" AutoPostBack="true" OnSelectedIndexChanged="GetByr_SelectedIndexChanged">
                                        <asp:ListItem>-</asp:ListItem>
                                    </asp:DropDownList>
                                </td>
                             </tr>
                         
                          <tr>
                                <td height="18px" width="100px">
                                    <span class="text-primary">Style/Order</span>
                                </td>
                                <td>
                                     <asp:DropDownList ID="GetStn" runat="server" CssClass="textbox" Width="200px" AutoPostBack="true" OnSelectedIndexChanged="GetStn_SelectedIndexChanged">
                                        <asp:ListItem>-</asp:ListItem>
                                    </asp:DropDownList>
                                </td>
                              </tr>
                        
                             <tr>
                                <td height="18px" width="100px">
                                    <span class="text-primary">Article</span>
                                </td>
                                <td>
                                     <asp:DropDownList ID="GetArticle" runat="server" CssClass="textbox" Width="200px" AutoPostBack="true" OnSelectedIndexChanged="GetArticle_SelectedIndexChanged">
                                        <asp:ListItem>-</asp:ListItem>
                                    </asp:DropDownList>
                                </td>
                              </tr>      
                            
                         <tr>
                              <td height="18px" width="100px">
                                    <span class="text-primary">Garments Type </span>
                                </td>
                                <td>
                                    <asp:TextBox ID="GetGType" runat="server" CssClass="textbox" Width="200px">                                       
                                    </asp:TextBox>
                                </td>
                            </tr>
                         <tr>
                             <td height="18px" width="180px"></td>
                         </tr>
                         <tr>
                             <td>
                                 <asp:Button ID="btnPrint" runat="server" CssClass="Btn btn-primary" Text="EDIT LAYOUT" Width="170px"
                                            OnClick="btnPrint_Click"/>
                             </td>
                             <td></td>
                             
                         </tr>
                           

                         </table>
                     

                </fieldset>
            </div>
            <div>
                <asp:GridView ID="GridView1" runat="server" DataKeyNames="id" OnRowEditing="OnRowEditing" OnRowCancelingEdit="OnRowCancelingEdit" OnRowUpdating="OnRowUpdating" AutoGenerateEditButton="true" AutoGenerateDeleteButton="True" OnRowDeleting="OnRowDeleting">
                </asp:GridView>
            </div>
        </ContentTemplate>
        </asp:UpdatePanel>
</asp:Content>

